### ISSUE TITLE
Example for scheduling jobs that require GPUs

### ISSUE THREAD

**Issue by hemildesai** [aws-samples/aws-plugin-for-slurm#2]
Is it possible to provide an example to enable scheduling jobs requiring GPUs? In particular, how would I modify the slurm conf to allow support for provisioning GPU nodes (p2 and p3), and how would I schedule jobs requiring GPU nodes?

**Comment by amrragab8080** [comment]
Hi @hemildesai, this is possible. You will need to make a couple of changes. 
1) First the you will need to update [slurm-aws-startup.sh#L64](https://github.com/aws-samples/aws-plugin-for-slurm/blob/master/slurm-aws-startup.sh#L64) to change one of the instance types to point to either p2 or p3 instance type.

2) Notice that in the [slurm-compute.sh#L51](https://github.com/aws-samples/aws-plugin-for-slurm/blob/master/slurm-compute.sh#L51) We are actively calculating the number of GPUs if /dev/nvidiaX is detected so you need to provide a compute AMI that has the NVIDIA drivers installed. As part of standing up the nodes, gres.conf is filled automatically.
 
3) However since we are designating a specific instance type you will need to update slurm.conf to include a static stanza for the GPU nodes you are considering. For example if you use **p3.8xlarge**, you will need to add this to the slurm.conf for the Node partition that you designate.

`NodeName=ip-10-0-1-[6-250] CPUs=32 Feature=us-west-2a Gres=gpu:volta:4 State=Cloud`

**Comment by hemildesai** [comment]
Awesome, thanks for the information @amrragab8080 
I'm also getting 
```
sbatch --mem-per-cpu=1000 test.sbatch
sbatch: error: Memory specification can not be satisfied
sbatch: error: Batch job submission failed: Requested node configuration is not available
```
when trying to request memory per cpu. I tried setting `RealMemory` in the node specification, but then the jobs fail immediately. 

Do you know how to accomplish the above task?

**Comment by amrragab8080** [comment]
Hi @hemildesai,
Yes I do, not only do you set RealMemory= on the slurm_nodes.conf file you need to also set DefMemPerCPU= and MaxMemPerCPU= on the partition level and change SelectTypeParameters=CR_Core_Memory in slurm.conf.

**Comment by amrragab8080** [comment]
Since this thread is about GPU scheduling and bursting I will close it out. Re-open if there are issues on the GPU scheduling. Consider that SchedMD can help with additional slurm.conf scheduling optimizations.
