### ISSUE TITLE
Recommendation for sharing conda environments across workers

### ISSUE THREAD

**Issue by stephen-thomas** [aws-samples/aws-plugin-for-slurm#8]
I am configuring a cluster based on this repository and trying to establish a solution to share conda environments across the worker nodes.

As an initial setup I setup an EFS for one of our scientists to use as a development directory. However, we have been experiencing very high latencies while developing inside of this EFS.

What is your recommendation for a configuration like this?

The requirement is to be able to share conda environments across workers. Would an EBS volume similar to the /nfs/ be a better solution for this?

**Comment by amrragab8080** [comment]
This sounds like a configuration on the EFS layer - and make sure the backend I/O is providing enough throughput for your workload. Did you look into [Provisioned IOPS on the EFS layer](https://docs.aws.amazon.com/efs/latest/ug/performance.html)?

The /nfs layer should only be used for the slurm communication since its sharing the binaries and configuration files.
